
from sqlalchemy import Column, String, Integer, Float, Boolean, DateTime
from sqlalchemy.dialects.postgresql import UUID
from app.models.base import BaseModel
import uuid
from datetime import datetime

class PathologyRecord(BaseModel):
    __tablename__ = "pathology_records"
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    reference_code = Column(String, index=True, nullable=False)
    status = Column(String, default="ACTIVE")
    assigned_staff_id = Column(UUID(as_uuid=True), nullable=True)
    cost = Column(Float, default=0.0)
    requires_review = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    custom_field_1 = Column(String, nullable=True)
    custom_field_2 = Column(String, nullable=True)
    custom_field_3 = Column(String, nullable=True)
    custom_field_4 = Column(String, nullable=True)
    custom_field_5 = Column(String, nullable=True)
    custom_field_6 = Column(String, nullable=True)
    custom_field_7 = Column(String, nullable=True)
    custom_field_8 = Column(String, nullable=True)
    custom_field_9 = Column(String, nullable=True)
    custom_field_10 = Column(String, nullable=True)
    custom_field_11 = Column(String, nullable=True)
    custom_field_12 = Column(String, nullable=True)
    custom_field_13 = Column(String, nullable=True)
    custom_field_14 = Column(String, nullable=True)
    custom_field_15 = Column(String, nullable=True)
    custom_field_16 = Column(String, nullable=True)
    custom_field_17 = Column(String, nullable=True)
    custom_field_18 = Column(String, nullable=True)
    custom_field_19 = Column(String, nullable=True)
    custom_field_20 = Column(String, nullable=True)
    custom_field_21 = Column(String, nullable=True)
    custom_field_22 = Column(String, nullable=True)
    custom_field_23 = Column(String, nullable=True)
    custom_field_24 = Column(String, nullable=True)
    custom_field_25 = Column(String, nullable=True)
    custom_field_26 = Column(String, nullable=True)
    custom_field_27 = Column(String, nullable=True)
    custom_field_28 = Column(String, nullable=True)
    custom_field_29 = Column(String, nullable=True)
    custom_field_30 = Column(String, nullable=True)
    custom_field_31 = Column(String, nullable=True)
    custom_field_32 = Column(String, nullable=True)
    custom_field_33 = Column(String, nullable=True)
    custom_field_34 = Column(String, nullable=True)
    custom_field_35 = Column(String, nullable=True)
    custom_field_36 = Column(String, nullable=True)
    custom_field_37 = Column(String, nullable=True)
    custom_field_38 = Column(String, nullable=True)
    custom_field_39 = Column(String, nullable=True)
    custom_field_40 = Column(String, nullable=True)
    custom_field_41 = Column(String, nullable=True)
    custom_field_42 = Column(String, nullable=True)
    custom_field_43 = Column(String, nullable=True)
    custom_field_44 = Column(String, nullable=True)
    custom_field_45 = Column(String, nullable=True)
    custom_field_46 = Column(String, nullable=True)
    custom_field_47 = Column(String, nullable=True)
    custom_field_48 = Column(String, nullable=True)
    custom_field_49 = Column(String, nullable=True)
    custom_field_50 = Column(String, nullable=True)

